### ISSUE TITLE
Modules should be able to signal Service that something went wrong

### ISSUE THREAD

**Issue by Bogh** [smancke/guble#47]
Atm the `WebServer` is started inside a goroutine:
https://github.com/smancke/guble/blob/refactor/guble-24-public-router-interface/server/web_server.go#L25
It would be ideal if we can create an interface for modules to allow `Service` to know if something went wrong.

**Comment by smancke** [comment]
I'm not sure, what the Service than should do with that information.
Maybe it would be a good idea to have a toplevel health check resource in the service, which than calls a Healthcheck method on each module and aggregates these information.

**Comment by Bogh** [comment]
We can either shutdown the whole program or we can try to restart a service, including the webserver.
Although the webserver once started shouldn't have issues. But if the webserver doesn't start in the goroutine in the link specified above. The service assumes that the webserver is started. 

We can decide later what the service would do for each module, and just gracefully shutdown if something fails and log the error for now.
