### ISSUE TITLE
[PN-14] Clean shutdown

### ISSUE THREAD

**Issue by Bogh** [smancke/guble#50]
The main purpose here is: _Make sure the messages stored are sent out and no more messages are accepted_.
- After the `Router` has sent all the messages signal the `Service` to start to listen if all the modules finished.
- `Service` should listen for each `module` if the work is done, after calling Stop()
- Stop receiving messages.
- Wait to handle all messages that were received. 
- Websocket connection must be stopped gracefully.

Suggestion here is that the Stop method should return a channel that will be closed when work is done. Or the channel could also send an error and we log the error and consider the work is done also.

**Comment by smancke** [comment]
Sounds good.
In addition to that, we have to consider the right order of calling Stop() to ensure, that e.g. the router has no messages left in its channels, before calling stop on subscribers.

**Comment by Bogh** [comment]
True, I moved the `Router` issue on the first line.
